#ifndef FORESTNODE_H
#define FORESTNODE_H

#include <vector>
#include <iostream>
#include <climits>
#include <cstring>
#include <string>
#include <new>
#include "MatrixSize.h"
#include "AlignedMalloc.h"

static const int MAX_NUM_CHILDREN = 8;

/// One node of the forest generated by Forest.
/// The node name is stored in Forest.mNodeNames and the
/// length of the branch leading to this node as read from the file is in Forest.mBranchLengths
///
///     @author Mario Valle - Swiss National Supercomputing Centre (CSCS)
///     @date 2011-02-23 (initial version)
///     @version 1.0
///
///
struct ForestNode
{
	// Field order suggested by icc
	unsigned int				mOwnTree;					///< Per tree identifier
	unsigned int				mBranchId;					///< An unique index to access the branch length array (starts from zero at the first non-root node)
	ForestNode*					mParent;					///< Pointer to the node parent (null for the root)
#ifndef NEW_LIKELIHOOD
	double*						mProb[Nt];					///< Codons probability array (called g in the pseudocode) (can be computed by concurrent tree traversals)
#endif
	unsigned int				mInternalNodeId;			///< Internal node identifier to mark a branch as foreground. UINT_MAX means not an internal node
	std::vector<ForestNode *>	mChildrenList;				///< List of the node children
	unsigned int				mChildrenSameTreeFlags;		///< Bit i set if child i is in the same tree
	std::vector<int>			mSubtreeCodonsSignature;	///< List of codon idx for the subtree rooted at this node (after reduction it is emptied)
#ifndef NEW_LIKELIHOOD
	std::vector<double *>		mOtherTreeProb;				///< Pointers to other tree precomputed mProb, zero if not used, or local array if used from other tree
#endif

	/// Constructor
	///
	ForestNode()
	{
		mParent = 0;
#ifndef NEW_LIKELIHOOD
		memset(mProb, 0, Nt*sizeof(double*));
#endif
		setAllFlagsSameTree();
		mChildrenList.reserve(2);
	}

	/// Destructor
	///
	~ForestNode()
	{
		// Delete children if in the same tree. Delete partial Prob arrays if not pointer to other tree partial Prob array
		//std::vector<ForestNode*>::iterator irn;
		unsigned int i;
		unsigned int nc = mChildrenList.size();
		//for(irn=mChildrenList.begin(), i=0; irn != mChildrenList.end(); ++irn, ++i)
		for(i=0; i < nc; ++i)
		{
			if(isSameTree(i))
			{
				delete mChildrenList[i];

#ifndef NEW_LIKELIHOOD
				delete [] mOtherTreeProb[i];
#endif
			}
		}

		// Clean all arrays
		mChildrenList.clear();
		mSubtreeCodonsSignature.clear();
#ifndef NEW_LIKELIHOOD
		mOtherTreeProb.clear();
#endif
	}

	/// Copy constructor
	///
	/// @param[in] aNode Node that has to be assigned to the current node
	///
	ForestNode(const ForestNode& aNode)
	{
		mChildrenList			= aNode.mChildrenList;
		mParent					= aNode.mParent;
		mSubtreeCodonsSignature	= aNode.mSubtreeCodonsSignature;
#ifndef NEW_LIKELIHOOD
		memcpy(mProb, aNode.mProb, Nt*sizeof(double*));
#endif
		mInternalNodeId			= aNode.mInternalNodeId;
		mBranchId				= aNode.mBranchId;
		mOwnTree				= aNode.mOwnTree;
#ifndef NEW_LIKELIHOOD
		mOtherTreeProb			= aNode.mOtherTreeProb;
#endif
		mChildrenSameTreeFlags	= aNode.mChildrenSameTreeFlags;
	}

	/// Assignment operator
	///
	/// @param[in] aNode Node that has to be assigned to the current node
	///
	/// @return The node itself
	///
	ForestNode& operator=(const ForestNode& aNode)
	{
		// Make sure not same object
		if(this != &aNode)
		{
			mChildrenList			= aNode.mChildrenList;
			mParent					= aNode.mParent;
			mSubtreeCodonsSignature	= aNode.mSubtreeCodonsSignature;
#ifndef NEW_LIKELIHOOD
			memcpy(mProb, aNode.mProb, Nt*sizeof(double*));
#endif
			mInternalNodeId			= aNode.mInternalNodeId;
			mBranchId				= aNode.mBranchId;
			mOwnTree				= aNode.mOwnTree;
#ifndef NEW_LIKELIHOOD
			mOtherTreeProb			= aNode.mOtherTreeProb;
#endif
			mChildrenSameTreeFlags	= aNode.mChildrenSameTreeFlags;
		}

		// Return ref for multiple assignment
		return *this;
	}

	/// Build a node aligned to a 64 bits boundary (cache line size)
	///
	/// @param[in] aSize The size to be allocated
	///
	/// @return Pointer to the allocated memory area
	///
	/// @exception std::bad_alloc If no memory available
	///
	void* operator new(std::size_t aSize)
	{
		void *m = alignedMalloc(aSize, CACHE_LINE_ALIGN);
		if(!m) throw std::bad_alloc();
		return m;
	}

	/// Release the node
	///
	/// @param[in] aPtr Pointer to the memory area to be released
	///
	void operator delete(void* aPtr)
	{
		alignedFree(aPtr);
	}

	void* operator new(std::size_t /* aSize */, ForestNode* aHere)
	{
		return aHere;
	}

	void operator delete(void* /* aPtr */, ForestNode* /* aHere */)
	{
		// Do nothing
	}

	/// Print from this node down
	///
	/// @param[in] aNodeNames The list of node names
	/// @param[in] aOut Output stream
	/// @param[in] aIndent Initial number of indent spaces
	/// @param[in] aIncrement The indent amount is incremented by this value at each level
	///
	void print(const std::vector<std::string>& aNodeNames, std::ostream& aOut=std::cerr, unsigned int aIndent=0, unsigned int aIncrement=3) const
	{
		unsigned int i;

		// Indent
		for(i=0; i < aIndent; ++i) aOut << ' ';

		// Print the name
		aOut << '<' << ((mBranchId  != UINT_MAX) ? aNodeNames[mBranchId+1] : aNodeNames[0]) << "> ";
	
		// Print the ID
		if(mInternalNodeId != UINT_MAX) aOut << '(' << mInternalNodeId << '|' << mBranchId << ") ";
		else                            aOut << '('                    << '|' << mBranchId << ") ";

		// Print the indexes of the codons accumulated till this node
		std::vector<int>::const_iterator ig;
		for(ig=mSubtreeCodonsSignature.begin(); ig != mSubtreeCodonsSignature.end(); ++ig) aOut << *ig << ' ';
		aOut << std::endl;

		// Print the subtree
		std::vector<ForestNode*>::const_iterator irn;
		for(irn=mChildrenList.begin(), i=0; irn != mChildrenList.end(); ++irn, ++i)
		{
			// If the subtree is on the same tree, then print it, otherwise print only the subtree root node name.
			if(isSameTree(i))
			{
				(*irn)->print(aNodeNames, aOut, aIndent+aIncrement, aIncrement);
			}
			else
			{
				for(i=0; i < aIndent+aIncrement; ++i) aOut << ' ';
				i = (*irn)->mBranchId+1;
				aOut << '[' << aNodeNames[i] << ']' << std::endl;
			}
		}
	}

	/// Create a list of pointers to leaves.
	///
	/// @param[out] aLeafsList Pointers to leaves are pushed to this vector
	///
	void pushLeaf(std::vector<ForestNode*>& aLeafsList)
	{
		if(mChildrenList.empty())
		{
			aLeafsList.push_back(this);
		}
		else
		{
			std::vector<ForestNode*>::const_iterator irn;
			for(irn=mChildrenList.begin(); irn != mChildrenList.end(); ++irn) (*irn)->pushLeaf(aLeafsList);
		}
	}

	/// Fills the mSubtreeCodonsSignature list with the ordered union of its children's lists.
	///
	void gatherCodons(void)
	{
		std::vector<ForestNode*>::const_iterator irn;
		for(irn=mChildrenList.begin(); irn != mChildrenList.end(); ++irn)
		{
			(*irn)->gatherCodons();
			mSubtreeCodonsSignature.insert(mSubtreeCodonsSignature.end(), (*irn)->mSubtreeCodonsSignature.begin(), (*irn)->mSubtreeCodonsSignature.end());
		}
	}

	/// Count the total branches in the forest
	///
	/// @param[in] aAggressiveStrategy If true use the aggressive simplification strategy
	///
	unsigned int countBranches(bool aAggressiveStrategy=false) const
	{
		unsigned int cnt = 0;
		unsigned int i;

		// Visit the subtrees
		std::vector<ForestNode*>::const_iterator irn;
		for(irn=mChildrenList.begin(), i=0; irn != mChildrenList.end(); ++irn, ++i)
		{
			// If the subtree is on the same tree, then print it, otherwise print only the subtree root node name.
			if(isSameTree(i))
			{
				cnt += (*irn)->countBranches(aAggressiveStrategy)+1;
			}
			else if(!aAggressiveStrategy)
			{
				cnt += 1;
			}
		}
	
		return cnt;
	}

	/// Bitmask for the mChildrenSameTreeFlags bitset
	///
	static const unsigned int mMaskTable[MAX_NUM_CHILDREN];

	/// Mark child aChildIndex as not in the same tree (Reset the given flag to false)
	///
	/// @param[in] aChildIndex The index of the flag to be set to false
	///
	void markNotSameTree(unsigned int aChildIndex)
	{
		mChildrenSameTreeFlags &= ~mMaskTable[aChildIndex];
	}

	/// Test the given flag
	///
	/// @param[in] aChildIndex The index of the flag to be tested
	///
	/// @return The flag status
	///
	bool isSameTree(unsigned int aChildIndex) const
	{
		return (mChildrenSameTreeFlags & mMaskTable[aChildIndex]) == mMaskTable[aChildIndex];
	}

	/// Set all flags to true
	///
	void setAllFlagsSameTree(void)
	{
		mChildrenSameTreeFlags = UINT_MAX;
	}
};

#endif

