#!/bin/bash
#Environment variables for variety of example machines
#Please set these paths according to your system!

# 1) Local linux
  export BLAS_LIB_DIR="/home/userid/lib" #Path to BLAS library
  export LAPACK_LIB_DIR="/home/userid/lib" #Path to LAPACK library
  export NLOPT_LIB_DIR="/home/userid/lib/nlopt/lib" #Path to NLopt
  export NLOPT_INCLUDE_DIR="/home/userid/lib/nlopt/include"
  export MATH_LIB_NAMES="blas;lapack;lapack;blas;gfortranbegin;gfortran" #Change if your BLAS library is not libblas.a or if your LAPACK library is not liblapack.a. gfortranbegin/gfortran needed for GCC gfortran.
  export CXX="/usr/bin/mpicxx.mpich2" #Set this if using MPI

# 2) BG /Q
  export BLAS_LIB_DIR="/bgsys/local/lib64;/opt/ibmcmp/xlf/bg/14.1/lib64"
  export LAPACK_LIB_DIR="/bgsys/local/lib64;/opt/ibmcmp/xlf/bg/14.1/lib64"
  export NLOPT_LIB_DIR="/home/kali/FastCodeML-1.2.0/FCM-10.06.2014/nlopt-release/lib"
  export NLOPT_INCLUDE_DIR="/home/kali/FastCodeML-1.2.0/FCM-10.06.2014/nlopt-release/include"
  export MATH_LIB_NAMES="esslbg;lapack;m;xlf90_r;xl;xlfmath;esslbg;dl"
  export BOOST_ROOT="/home/kali/FastCodeML-1.2.0/FCM-10.06.2014/boost-release"
  export INCLUDE_DIR_MKL="/bgsys/ibm_essl/prod/opt/ibmmath/essl/5.1/include"
  export CXX="/bgsys/drivers/ppcfloor/comm/xl/bin/mpixlcxx"
  export CXXFLAGS="-qstrict -qthreaded -qhalt=e -D_BGQ_COMPILER"
  export LDFLAGS="-static"

# 3) Vital-IT
  export BLAS_LIB_DIR="/software/Utility/OpenBLAS/0.2.5/lib"
  export LAPACK_LIB_DIR="/software/Utility/OpenBLAS/0.2.5/lib"
  export NLOPT_INCLUDE_DIR="/software/Development/Libraries/nlopt/2.4.2/include"
  export NLOPT_LIB_DIR="/software/Development/Libraries/nlopt/2.4.2/lib64"
  export MATH_LIB_NAMES="openblas;lapack;gfortranbegin;gfortran"
  export BOOST_ROOT="/software/lib64/"
  export CXX=g++ # or to a cpp compiler with mpi support e.g. "/home/kali/lib/mpi/bin/mpicxx"



